local gh = function(x)
  return 'https://github.com/' .. x
end

vim.pack.add({
  { src = gh 'BirdeeHub/lze' },
  { src = gh 'BirdeeHub/lzextras' },
  { src = gh 'olimorris/onedarkpro.nvim' },
  { src = gh 'thesimonho/kanagawa-paper.nvim' },
  { src = gh 'f-person/auto-dark-mode.nvim' },
  { src = gh 'nvim-mini/mini.nvim' },
  { src = gh 'folke/snacks.nvim' },
  { src = gh 'neovim/nvim-lspconfig' },
  { src = gh 'mason-org/mason.nvim' },
  { src = gh 'mason-org/mason-lspconfig.nvim' },
  { src = gh 'WhoIsSethDaniel/mason-tool-installer.nvim' },
  { src = gh 'folke/lazydev.nvim' },
  { src = gh 'nvim-treesitter/nvim-treesitter', version = 'main' },
  { src = gh 'nvim-treesitter/nvim-treesitter-textobjects' },
  { src = gh 'stevearc/conform.nvim' },
  { src = gh 'Saghen/blink.cmp', version = vim.version.range '1.*' },
  { src = gh 'xzbdmw/colorful-menu.nvim' },
  { src = gh 'mawkler/modicator.nvim' },
  { src = gh 'kevinhwang91/nvim-hlslens' },
  { src = gh 'stevearc/quicker.nvim' },
  { src = gh 'j-hui/fidget.nvim' },
  { src = gh 'nvim-lualine/lualine.nvim' },
  { src = gh 'lewis6991/gitsigns.nvim' },
  { src = gh 'folke/which-key.nvim' },
  { src = gh 'tpope/vim-sleuth' },
  { src = gh 'MeanderingProgrammer/render-markdown.nvim' },
  { src = gh 'YousefHadder/markdown-plus.nvim' },
  { src = gh 'nvim-lua/plenary.nvim' },
  { src = gh 'GustavEikaas/easy-dotnet.nvim', version = '640612c3d1f691ed47074ae0b262670057b18445' },
  { src = gh 'mfussenegger/nvim-dap' },
  { src = gh 'rcarriga/nvim-dap-ui' },
  { src = gh 'nvim-neotest/nvim-nio' },
  { src = gh 'nvim-neotest/neotest' },
  { src = gh 'nvim-neotest/neotest-python' },
  { src = gh 'mfussenegger/nvim-dap-python' },
  { src = gh 'mfussenegger/nvim-lint' },
}, { load = false })
